### ISSUE TITLE
Reading from Aidex CGM directly?

### ISSUE THREAD

**Issue by bertythomas** [andyrozman/AidexSendXdrip#1]
Hi,
Can this repo read directly from Aidex CGM or does it require us to first install the Aidex app? I couldn't find any NFC/ Bluetooth send/ receive commands in the repo and hence the question.
Thank you!

**Comment by andyrozman** [comment]
This repo was intended for Aidex (GlucoRx) team, to help them implement Broadcasting towards Xdrip and AAPS. It doesn't do anything... 
They have added broadcasting functionality to their application (not sure if it was released yet and where). At the moment AAPS supports receiving from Aidex App, for Xdrip you would need to look at my branch (and repo) and build it from there... But code is probably outdated... I haven't made any merges yet, and no PR was created for this functionality (I wanted to wait until they have actually released the implementation).
